In [6]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [7]:
#creating the dataset
hours = np.array([2,4,6,8,10]).reshape(-1,1)
marks = np.array([55,60,70,80,88])
hours,marks

(array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]]),
 array([55, 60, 70, 80, 88]))

In [8]:
model = LinearRegression()
model.fit(hours,marks)
pred = model.predict(hours)
print(pred)

[53.4 62.  70.6 79.2 87.8]


In [9]:
# compute matrics
mae = mean_absolute_error(marks,pred)
mse = mean_squared_error(marks, pred)
rmse = np.sqrt(mse)
r_squire = r2_score(marks,pred)

In [10]:
print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R-squared: {r_squire}")

Mean Absolute Error: 1.040000000000002
Mean Squared Error: 1.5200000000000011
Root Mean Squared Error: 1.2328828005937957
R-squared: 0.9898286937901499
